# -----------------WARNING WARNING WARNING-----------------
#         THE CODE BELOW WAS GENERATED BY DEEPSEEK
#                   SKYNET IS COMING
# -----------------WARNING WARNING WARNING-----------------

import math

def pte_to_str(pte):
    """Convert PTE to human-readable string representation"""
    permissions = [
        ('V', 0),
        ('R', 1),
        ('W', 2),
        ('X', 3),
        ('U', 4),
        ('G', 5),
        ('A', 6),
        ('D', 7),
        ('RSW', (8, 2))  # 2 bits starting at 8
    ]

    perm_str = []
    for name, bit in permissions:
        if isinstance(bit, tuple):
            mask = (1 << bit[1]) - 1
            val = (pte >> bit[0]) & mask
            perm_str.append(f"{name}={val}")
        else:
            val = (pte >> bit) & 1
            perm_str.append(f"{name}={val}")

    ppn = (pte >> 10) & ((1 << 44) - 1)  # Max 44 PPN bits for Sv48
    return f"PTE: 0x{pte:016x} [PPN: 0x{ppn:x}, {' '.join(perm_str)}]"


def generate_riscv_page_table(mappings, table_start, levels=3, va_bits=39, pa_bits=56, verbose=False):
    """
    Generate a complete RISC-V page table with correct address handling.

    Args:
        mappings: List of {'va':, 'pa':, 'permissions':, 'page_size':} dicts
        levels: Page table levels (2, 3, or 4)
        va_bits: Virtual address bits (32, 39, or 48)
        pa_bits: Physical address bits (typically 56)
        verbose: Print debug info

    Returns:
        Dictionary containing:
        - 'root_ppn': Root page table physical page number
        - 'ptes': List of all PTEs
        - 'pages': Physical memory pages used
    """
    PAGE_SIZE = 4096
    PTE_SIZE = 8
    PTES_PER_PAGE = PAGE_SIZE // PTE_SIZE

    # Validate architecture
    if levels not in {2, 3, 4}:
        raise ValueError("Levels must be 2 (Sv32), 3 (Sv39), or 4 (Sv48)")
    if (levels, va_bits) not in {(2, 32), (3, 39), (4, 48)}:
        raise ValueError(f"Invalid levels/va_bits combination: {levels}/{va_bits}")

    # Physical memory manager
    class PhysicalMemory:
        def __init__(self):
            self.next_addr = table_start # Start of memory for page tables
            self.pages = {}

        def allocate_page(self):
            addr = self.next_addr
            self.next_addr += PAGE_SIZE
            self.pages[addr] = [0] * PTES_PER_PAGE
            return addr

    pmem = PhysicalMemory()

    # Create root page table
    root_pt_addr = pmem.allocate_page()
    page_tables = {0: root_pt_addr}  # Level 0 -> root PT address
    pte_list = []

    def get_vpn(va, level):
        """Extract VPN for given level from VA"""
        shift = 12 + 9 * (levels - level - 1)
        return (va >> shift) & 0x1FF  # 9-bit VPN

    def make_pte(ppn, is_leaf, permissions):
        """Create a PTE with proper PPN and permissions"""
        pte = (ppn << 10) | permissions.get('V', 0)
        if is_leaf:
            pte |= (permissions.get('R', 0) << 1 |
                    permissions.get('W', 0) << 2 |
                    permissions.get('X', 0) << 3 |
                    permissions.get('U', 0) << 4 |
                    permissions.get('G', 0) << 5 |
                    permissions.get('A', 0) << 6 |
                    permissions.get('D', 0) << 7 |
                    (permissions.get('RSW', 0) & 0x3) << 8)
        else:
            pte |= 0x1  # Valid non-leaf PTE
        return pte

    # Process each mapping
    for mapping in mappings:
        va = mapping['va']
        pa = mapping['pa']
        perms = mapping.get('permissions', {'V': 1, 'R': 1})
        page_size = mapping.get('page_size', PAGE_SIZE)

        # Calculate target level (0 = root, levels-1 = leaf)
        target_level = levels - 1 - int(math.log2(page_size // PAGE_SIZE))
        target_level = max(0, target_level)  # Clamp to valid levels

        if verbose:
            print(f"\nMapping VA 0x{va:016x} -> PA 0x{pa:016x} (page_size: {page_size}, target_level: {target_level})")

        # Walk page table hierarchy
        current_pt_addr = root_pt_addr
        for level in range(levels):
            vpn = get_vpn(va, level)
            pte_idx = vpn
            current_pt = pmem.pages[current_pt_addr]

            if verbose:
                print(f"  Level {level}: PT @ 0x{current_pt_addr:016x}, VPN 0x{vpn:03x}, PTE index {pte_idx}")

            # Check if we're at or past target level
            if level >= target_level:
                # Create leaf PTE
                ppn = pa >> 12
                pte = make_pte(ppn, True, perms)
                current_pt[pte_idx] = pte
                pte_list.append((current_pt_addr, pte_idx, pte))
                if verbose:
                    print(f"    Created leaf PTE: {pte_to_str(pte)}")
                break
            else:
                # Non-leaf case
                if current_pt[pte_idx] == 0:
                    # Allocate new page table
                    new_pt_addr = pmem.allocate_page()
                    ppn = new_pt_addr >> 12
                    pte = make_pte(ppn, False, {})
                    current_pt[pte_idx] = pte
                    pte_list.append((current_pt_addr, pte_idx, pte))
                    page_tables[(level + 1) << 18 | vpn] = new_pt_addr
                    if verbose:
                        print(f"    Allocated new PT @ 0x{new_pt_addr:016x} (PPN 0x{ppn:x})")
                        print(f"    Created non-leaf PTE: {pte_to_str(pte)}")

                # Follow to next level
                current_pte = current_pt[pte_idx]
                if not (current_pte & 0x1):
                    raise RuntimeError("Invalid PTE during page table walk")
                current_pt_addr = ((current_pte >> 10) << 12)

    return {
        'root_ppn': root_pt_addr >> 12,
        'ptes': pte_list,
        'pages': pmem.pages,
        'next_phys_addr': pmem.next_addr
    }


TABLE_START = 0x80_0000_0000
# Example mappings
mappings = [
    {
        'va': 0x40_0000_0000,
        'pa': TABLE_START + 0x10000,
        'permissions': {'V': 1, 'R': 1, 'W': 1, 'U': 0},
        'page_size': 4096
    },
]

# Generate the page table
page_table = generate_riscv_page_table(mappings, TABLE_START, levels=3, pa_bits=40, verbose=True)

# -----------------WARNING WARNING WARNING-----------------
#         THE ABOVE CODE WAS GENERATED BY DEEPSEEK
#                   SKYNET IS COMING
# -----------------WARNING WARNING WARNING-----------------

def emit_8byte_zeroes(count):
    if count == 0:
        return
    bytes_to_fill = count * 8
    print(f"  .fill {bytes_to_fill}")

def dump_page_table_as_asm(pt):
    """Print the page table in a way suitable for consumption by assembler"""
    trd = {} # I use dictionary to traverse entries in sorted order
    for addr, ptes in pt['pages'].items():
        zero_counter = 0
        for i, pte in enumerate(ptes):
            if pte == 0:
                zero_counter = zero_counter + 1
                continue
            pte_as_hex = hex(pte)
            emit_8byte_zeroes(zero_counter)
            zero_counter = 0
            print(f"  .8byte {pte_as_hex}")
        emit_8byte_zeroes(zero_counter)
    # should we fill out more ?
    # emit_8byte_zeroes(4096)

print(
'''
--ASM STARTS HERE---
.global page_table
.global _entry
.text
page_table:
'''
)
dump_page_table_as_asm(page_table)
print(
'''
.balign 8
_entry:
  j _entry
'''
)

print("--LINKER SCRIPT HERE---")
print("ENTRY ( _entry ) SECTIONS { .text " + hex(TABLE_START) + ":  { *(.text) } }")

